### ISSUE TITLE
RawField exception after upgrading to 0.3.1

### ISSUE THREAD

**Issue by tcqiuyu** [pytorch/text#452]
After upgrading torchtext from 0.2.3 to 0.3.1, my code encountered a new exception as below:

```
  File "/Users/Qiu/workspace/TeleScopeNet/main.py", line 61, in <module>
    trainer.start_train()
  File "/Users/Qiu/workspace/TeleScopeNet/train.py", line 75, in start_train
    avg_loss = self.train_epoch(model, train_dataloader, epoch, optimizer)
  File "/Users/Qiu/workspace/TeleScopeNet/train.py", line 94, in train_epoch
    total=ceil(total_len / self.params['batch_size'])):
  File "/Users/Qiu/anaconda3/envs/telescope/lib/python3.6/site-packages/tqdm/_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "/Users/Qiu/anaconda3/envs/telescope/lib/python3.6/site-packages/torchtext/data/iterator.py", line 157, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "/Users/Qiu/anaconda3/envs/telescope/lib/python3.6/site-packages/torchtext/data/batch.py", line 26, in __init__
    self.input_fields = [k for k, v in dataset.fields.items() if
  File "/Users/Qiu/anaconda3/envs/telescope/lib/python3.6/site-packages/torchtext/data/batch.py", line 27, in <listcomp>
    v is not None and not v.is_target]
AttributeError: 'RawField' object has no attribute 'is_target'`
```

I used RawField because I intended to add some values that does not require any modification to the dataset. But now there seems some changes around here. I am wondering if RawField behaves the same as before? Thanks for any help in advance!

**Comment by tcqiuyu** [comment]
I just found a previous issue in #442. The work around works fine for me. This issue can be closed:)

**Comment by mttk** [comment]
@tcqiuyu this will also be fixed soon, although in master. I might do a quick update on the release if this is a common use-case.
