### ISSUE TITLE
can't pickle torch.dtype objects

### ISSUE THREAD

**Issue by linhx13** [pytorch/text#350]
torch (0.4.0)
torchtext (0.3.0)

Hello, I got an error when pickling Field.

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    dill.dump(field, open('./f.pkl', 'wb'))
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/site-packages/dill/_dill.py", line 286, in dump
    pik.dump(obj)
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/site-packages/dill/_dill.py", line 893, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/opt/userhome/ichongxiang/.conda/envs/py27/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
TypeError: can't pickle torch.dtype objects
```

It seems that an torch.dtype does not have __reduce__() method. Any suggestion to work around?

**Comment by domaala** [comment]
According to [this discussion](https://github.com/pytorch/pytorch/issues/7481), this has been fixed in pytorch 0.4.1. I've double-checked and I can indeed deepcopy a `dtype` object.

**Comment by fernandocamargoti** [comment]
I have PyTorch 0.4.1 and the error still occurs. I've tried the @notnami workaround, but I receive:

'torch' has no attribute 'float32'

**Comment by domaala** [comment]
@fernandocamargoti Please, try this:

```
import torch
from copy import deepcopy

deepcopy(torch.float32)
```

This **should** work on PyTorch 0.4.1.

**Comment by notnami** [comment]
As of Pytorch 0.4.1, this is no longer a problem, so I think this issue should be closed.
